export const GENRES = [
  { id: 28, name: "Боевик" },
  { id: 12, name: "Приключения" },
  { id: 16, name: "Мультфильм" },
  { id: 35, name: "Комедия" },
  { id: 80, name: "Криминал" },
  { id: 99, name: "Документальный" },
  { id: 18, name: "Драма" },
  { id: 10751, name: "Семейный" },
  { id: 14, name: "Фэнтези" },
  { id: 36, name: "История" },
  { id: 27, name: "Ужасы" },
  { id: 10402, name: "Музыка" },
  { id: 9648, name: "Детектив" },
  { id: 10749, name: "Мелодрама" },
  { id: 878, name: "Фантастика" },
  { id: 10770, name: "Телефильм" },
  { id: 53, name: "Триллер" },
  { id: 10752, name: "Военный" },
  { id: 37, name: "Вестерн" },
];

export const COUNTRIES = [
  { code: "US", name: "США" },
  { code: "RU", name: "Россия" },
  { code: "FR", name: "Франция" },
  { code: "GB", name: "Великобритания" },
  { code: "DE", name: "Германия" },
  { code: "JP", name: "Япония" },
  { code: "IT", name: "Италия" },
  { code: "IN", name: "Индия" },
  { code: "KR", name: "Южная Корея" },
  { code: "ES", name: "Испания" },
  { code: "CN", name: "Китай" },
  { code: "CA", name: "Канада" },
  { code: "AU", name: "Австралия" },
  { code: "BR", name: "Бразилия" },
  { code: "SE", name: "Швеция" },
  { code: "DK", name: "Дания" },
  { code: "FI", name: "Финляндия" },
  { code: "PL", name: "Польша" },
  { code: "UA", name: "Украина" },
  { code: "TR", name: "Турция" },
];
